version: '3.8'

services:
  web:
    build: .
    ports:
      - "8002:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - SECRET_KEY=your-secret-key-here
      - DEBUG=False
      - DB_NAME=doctor_appointment
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=your-email@gmail.com
      - EMAIL_HOST_PASSWORD=your-app-password
      - STRIPE_PUBLISHABLE_KEY=your-stripe-publishable-key
      - STRIPE_SECRET_KEY=your-stripe-secret-key
      - STRIPE_WEBHOOK_SECRET=your-stripe-webhook-secret
      - RAZORPAY_KEY_ID=your-razorpay-key-id
      - RAZORPAY_KEY_SECRET=your-razorpay-key-secret
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=doctor_appointment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres_data:
